// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xNNdbe_c-W3RbyIOaNHBXMqqgJSEIbg',
    appId: '1:199246698222:web:90bfe9c416fc266ba6c5ff',
    messagingSenderId: '199246698222',
    projectId: 'fir-76fa5',
    authDomain: 'fir-76fa5.firebaseapp.com',
    storageBucket: 'fir-76fa5.appspot.com',
    measurementId: 'G-B06MLVF479',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuz1U-A5ZR0i9_9SsnmwMMSvWkcknwV3Q',
    appId: '1:199246698222:android:b9038f4596a88c4aa6c5ff',
    messagingSenderId: '199246698222',
    projectId: 'fir-76fa5',
    storageBucket: 'fir-76fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_zXWzLsmVTToXr0mtN5wWb6KCprFFIgo',
    appId: '1:199246698222:ios:249ba926278390c4a6c5ff',
    messagingSenderId: '199246698222',
    projectId: 'fir-76fa5',
    storageBucket: 'fir-76fa5.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_zXWzLsmVTToXr0mtN5wWb6KCprFFIgo',
    appId: '1:199246698222:ios:249ba926278390c4a6c5ff',
    messagingSenderId: '199246698222',
    projectId: 'fir-76fa5',
    storageBucket: 'fir-76fa5.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_xNNdbe_c-W3RbyIOaNHBXMqqgJSEIbg',
    appId: '1:199246698222:web:69d1f720156c6915a6c5ff',
    messagingSenderId: '199246698222',
    projectId: 'fir-76fa5',
    authDomain: 'fir-76fa5.firebaseapp.com',
    storageBucket: 'fir-76fa5.appspot.com',
    measurementId: 'G-CBEZQFYMM2',
  );
}
